worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

# service_template_db_1 is the service name + _ + filename of the db_1.sql
dbconnection: 'postgresql://testsuite@localhost:15433/service_template_db_1'
